import { contextBridge, ipcRenderer } from 'electron'

const api = {
  info: () => ipcRenderer.invoke('app:info'),
  listDevices: () => ipcRenderer.invoke('devices:list'),
  getConfig: () => ipcRenderer.invoke('devices:config'),
  findDevices: () => ipcRenderer.invoke('devices:find'),
  testDevices: (systemId: string, micId: string) => ipcRenderer.invoke('devices:test', systemId, micId),
  stopScan: () => ipcRenderer.invoke('devices:stopScan'),
  saveDevices: (systemId: string, micId: string) => ipcRenderer.invoke('devices:save', systemId, micId),
  snapshot: (label: string) => ipcRenderer.invoke('devices:snapshot', label),
  setKey: (key: string) => ipcRenderer.invoke('key:set', key),
  start: () => ipcRenderer.invoke('session:start'),
  stillHere: () => ipcRenderer.invoke('session:stillHere'),
  setAppSettings: (s: unknown) => ipcRenderer.invoke('app:setSettings', s),
  callsInfo: () => ipcRenderer.invoke('calls:info'),
  confirmRetention: (yes: boolean) => ipcRenderer.invoke('calls:confirmRetention', yes),
  deleteAllCalls: () => ipcRenderer.invoke('calls:deleteAll'),
  onRetentionPreview: (cb: (p: { days: number; calls: Array<{ started_at: string; account: string }> }) => void) => ipcRenderer.on('retention-preview', (_e, p) => cb(p)),
  pause: () => ipcRenderer.invoke('session:pause'),
  resume: () => ipcRenderer.invoke('session:resume'),
  stop: () => ipcRenderer.invoke('session:stop'),
  switchEndpoint: (stream: string, id: string) => ipcRenderer.invoke('session:switchEndpoint', stream, id),
  openFolder: () => ipcRenderer.invoke('app:openFolder'),
  buildInfo: () => ipcRenderer.invoke('app:build'),
  supportFiles: () => ipcRenderer.invoke('app:supportFiles'),
  helpInfo: () => ipcRenderer.invoke('help:info'),
  helpCheckReady: () => ipcRenderer.invoke('help:checkReady'),
  helpPress: () => ipcRenderer.invoke('help:press'),
  helpFeedback: (fb: unknown) => ipcRenderer.invoke('help:feedback', fb),
  helpCallCards: () => ipcRenderer.invoke('help:callCards'),
  helpSetSettings: (s: unknown) => ipcRenderer.invoke('help:setSettings', s),
  helpSetSetup: (s: unknown) => ipcRenderer.invoke('help:setSetup', s),
  helpSetLabel: (l: unknown) => ipcRenderer.invoke('help:setLabel', l),
  helpLabels: () => ipcRenderer.invoke('help:labels'),
  helpCallNotes: () => ipcRenderer.invoke('help:callNotes'),
  onCallNotes: (cb: (s: unknown) => void) => ipcRenderer.on('call-notes', (_e, s) => cb(s)),
  // M3 call plan: the setup strip's "Must learn" box
  helpSetMustLearn: (items: string[]) => ipcRenderer.invoke('help:setMustLearn', items),
  wrapupRemoveToLearn: (item: string) => ipcRenderer.invoke('wrapup:removeToLearn', item),
  helpSetKey: (key: string) => ipcRenderer.invoke('help:setKey', key),
  knowledgeList: () => ipcRenderer.invoke('knowledge:list'),
  knowledgeReindex: () => ipcRenderer.invoke('knowledge:reindex'),
  knowledgeApprove: (docId: string, approved: boolean) => ipcRenderer.invoke('knowledge:approve', docId, approved),
  knowledgeImport: (mode: 'folder' | 'files') => ipcRenderer.invoke('knowledge:import', mode),
  knowledgeRemove: (docId: string) => ipcRenderer.invoke('knowledge:remove', docId),
  knowledgeOpenFolder: () => ipcRenderer.invoke('knowledge:openFolder'),
  playbookOpen: () => ipcRenderer.invoke('playbook:open'),
  playbookInfo: () => ipcRenderer.invoke('playbook:info'),
  playbookUseBuiltIn: () => ipcRenderer.invoke('playbook:useBuiltIn'),
  playbookKeepMine: () => ipcRenderer.invoke('playbook:keepMine'),
  helpBenchmark: (opts: unknown) => ipcRenderer.invoke('help:benchmark', opts),
  helpOpenReport: (file: string) => ipcRenderer.invoke('help:openReport', file),
  helpSaveMoment: (cardId: string) => ipcRenderer.invoke('help:saveMoment', cardId),
  practiceInfo: () => ipcRenderer.invoke('practice:info'),
  practiceOpenFolder: () => ipcRenderer.invoke('practice:openFolder'),
  helpExportFeedback: (period: string) => ipcRenderer.invoke('help:exportFeedback', period),
  onBenchmarkProgress: (cb: (p: { done: number; total: number; scenario: string; ok: boolean }) => void) => ipcRenderer.on('benchmark-progress', (_e, p) => cb(p)),
  onHelp: (cb: (ev: unknown) => void) => ipcRenderer.on('help-event', (_e, ev) => cb(ev)),
  onHelpNotice: (cb: (msg: string) => void) => ipcRenderer.on('help-notice', (_e, msg) => cb(msg)),
  onHelpReady: (cb: (r: { readiness: string; message: string }) => void) => ipcRenderer.on('help-ready', (_e, r) => cb(r)),
  onHelpFocus: (cb: () => void) => ipcRenderer.on('help-focus', () => cb()),
  onIdle: (cb: (s: { warning: boolean; seconds?: number }) => void) => ipcRenderer.on('idle', (_e, s) => cb(s)),
  onAppNotice: (cb: (n: { level: 'warning' | 'info' | 'error'; text: string }) => void) => ipcRenderer.on('app-notice', (_e, n) => cb(n)),
  onAppSettings: (cb: (s: { hide_from_capture: boolean; retention_days: number | null }) => void) => ipcRenderer.on('app-settings', (_e, s) => cb(s)),
  onSession: (cb: (ev: unknown) => void) => ipcRenderer.on('session-event', (_e, ev) => cb(ev)),
  onScan: (cb: (ev: unknown) => void) => ipcRenderer.on('scan-event', (_e, ev) => cb(ev)),
  helpWrap: () => ipcRenderer.invoke('help:wrap'),
  setCompact: (on: boolean) => ipcRenderer.invoke('window:compact', on) as Promise<{ compact: boolean }>,
  memoryAccounts: () => ipcRenderer.invoke('memory:accounts'),
  memoryAccount: (account: string) => ipcRenderer.invoke('memory:account', account),
  onCallsDeleted: (cb: () => void) => ipcRenderer.on('calls-deleted', () => cb()),
  // M2 wrap-up after Stop and the follow-up draft
  wrapupGet: () => ipcRenderer.invoke('wrapup:get'),
  wrapupUpdateItem: (change: unknown) => ipcRenderer.invoke('wrapup:updateItem', change),
  wrapupAddItem: (item: unknown) => ipcRenderer.invoke('wrapup:addItem', item),
  wrapupDraft: () => ipcRenderer.invoke('wrapup:draft'),
  wrapupRetry: () => ipcRenderer.invoke('wrapup:retry'),
  onWrapup: (cb: (w: unknown) => void) => ipcRenderer.on('wrapup', (_e, w) => cb(w)),
  // M3 smarter presses: the latest buying signal of the call (the WRAP button's tag)
  helpSignal: () => ipcRenderer.invoke('help:signal') as Promise<{ kind: string; at_ms: number } | null>,
  onBuyingSignal: (cb: (s: { kind: string; at_ms: number } | null) => void) => ipcRenderer.on('buying-signal', (_e, s) => cb(s)),
  // M4 "What I know about <account>": Keith's notes per account, and the prep prompt he copies
  notesGet: (account: string) => ipcRenderer.invoke('notes:get', account) as Promise<{ account: string; text: string; updated_at: string | null } | null>,
  notesSet: (account: string, text: string) => ipcRenderer.invoke('notes:set', { account, text }) as Promise<{ account: string; text: string; updated_at: string | null } | null>,
  notesPrepend: (account: string, text: string, replace?: string) => ipcRenderer.invoke('notes:prepend', { account, text, replace }) as Promise<{ account: string; text: string; updated_at: string | null; dropped_lines: number } | null>,
  notesPrepPrompt: (account: string) => ipcRenderer.invoke('notes:prepPrompt', account) as Promise<string>,
}

contextBridge.exposeInMainWorld('copilot', api)
export type CopilotApi = typeof api
