import { contextBridge, ipcRenderer } from 'electron'

const api = {
  info: () => ipcRenderer.invoke('app:info'),
  listDevices: () => ipcRenderer.invoke('devices:list'),
  getConfig: () => ipcRenderer.invoke('devices:config'),
  findDevices: () => ipcRenderer.invoke('devices:find'),
  testDevices: (systemId: string, micId: string) => ipcRenderer.invoke('devices:test', systemId, micId),
  stopScan: () => ipcRenderer.invoke('devices:stopScan'),
  saveDevices: (systemId: string, micId: string) => ipcRenderer.invoke('devices:save', systemId, micId),
  snapshot: (label: string) => ipcRenderer.invoke('devices:snapshot', label),
  setKey: (key: string) => ipcRenderer.invoke('key:set', key),
  start: () => ipcRenderer.invoke('session:start'),
  pause: () => ipcRenderer.invoke('session:pause'),
  resume: () => ipcRenderer.invoke('session:resume'),
  stop: () => ipcRenderer.invoke('session:stop'),
  switchEndpoint: (stream: string, id: string) => ipcRenderer.invoke('session:switchEndpoint', stream, id),
  openFolder: () => ipcRenderer.invoke('app:openFolder'),
  helpInfo: () => ipcRenderer.invoke('help:info'),
  helpPress: () => ipcRenderer.invoke('help:press'),
  helpFeedback: (fb: unknown) => ipcRenderer.invoke('help:feedback', fb),
  helpSetSettings: (s: unknown) => ipcRenderer.invoke('help:setSettings', s),
  helpSetSetup: (s: unknown) => ipcRenderer.invoke('help:setSetup', s),
  helpSetLabel: (l: unknown) => ipcRenderer.invoke('help:setLabel', l),
  helpLabels: () => ipcRenderer.invoke('help:labels'),
  helpSetKey: (key: string) => ipcRenderer.invoke('help:setKey', key),
  knowledgeList: () => ipcRenderer.invoke('knowledge:list'),
  knowledgeReindex: () => ipcRenderer.invoke('knowledge:reindex'),
  knowledgeApprove: (docId: string, approved: boolean) => ipcRenderer.invoke('knowledge:approve', docId, approved),
  knowledgeImport: (mode: 'folder' | 'files') => ipcRenderer.invoke('knowledge:import', mode),
  knowledgeRemove: (docId: string) => ipcRenderer.invoke('knowledge:remove', docId),
  knowledgeOpenFolder: () => ipcRenderer.invoke('knowledge:openFolder'),
  playbookOpen: () => ipcRenderer.invoke('playbook:open'),
  helpBenchmark: (opts: unknown) => ipcRenderer.invoke('help:benchmark', opts),
  helpOpenReport: (file: string) => ipcRenderer.invoke('help:openReport', file),
  onBenchmarkProgress: (cb: (p: { done: number; total: number; scenario: string; ok: boolean }) => void) => ipcRenderer.on('benchmark-progress', (_e, p) => cb(p)),
  onHelp: (cb: (ev: unknown) => void) => ipcRenderer.on('help-event', (_e, ev) => cb(ev)),
  onHelpNotice: (cb: (msg: string) => void) => ipcRenderer.on('help-notice', (_e, msg) => cb(msg)),
  onSession: (cb: (ev: unknown) => void) => ipcRenderer.on('session-event', (_e, ev) => cb(ev)),
  onScan: (cb: (ev: unknown) => void) => ipcRenderer.on('scan-event', (_e, ev) => cb(ev)),
}

contextBridge.exposeInMainWorld('copilot', api)
export type CopilotApi = typeof api
